### ISSUE TITLE
Diseño de caso de uso X

### ISSUE THREAD

**Issue by Ruskab** [rup-projects/rup-projects#183]

**Comment by plfgavilan** [comment]
@Ruskab He echado un ojo al diagrama con el diseño, lo veo muy bien, sólo tengo un par de preguntillas:

En este fragmento:

![image](https://user-images.githubusercontent.com/4791544/91645359-b8f59780-ea44-11ea-865d-60bb71a3c4f6.png)

Creo que en realidad es la vista la que conoce al presentador. Ya que es esta la que llama a funciones del presentador:

XTemplate -- > XComponent

Y en cuanto a esto:

![image](https://user-images.githubusercontent.com/4791544/91645413-26092d00-ea45-11ea-8420-e730d49d7e3d.png)

¿Vamos a llamar finalmente "Service" a lo que hemos estado llamado controllers (con los metodos de los casos de uso) cierto?

Por mi perfecto

**Comment by plfgavilan** [comment]
Por cierto, enlaza a esta issue el PR con el código del diagrama :-)

**Comment by Ruskab** [comment]
Pues la primera pergunta, si XTemplate -- > XComponent
desconozco algular no lo he usado, nunca, pero por la ultima reunion me parecio entender que en angular al final era el XComponent - TypeScript/JavaScript (presentador) el que conocia la vista y le decia como tenia que pintarse, pero como nunca lo he usado no lo puedo asegurar. 

Lo que si que he trabajado es como JSF en java, 
![image](https://user-images.githubusercontent.com/16058725/91645922-17714480-ea4a-11ea-8230-9713f2c1ec9a.png)

Y alli digamos que desde la vista Xtemplate tu vas llamando metodos de XBean por lo que diria que es la vista que conoce a ese "controlador / presentador" no se que es exactamente.  

Pero con esa tecnologia podria pasar que tu desde el Bean modifiques la Vista con metodos especiales pero no es lo habitual, asi que en ese caso lo dejaria como tan Xtemplate --> XBean

**Comment by Ruskab** [comment]
Y la segunda pregunta, ese XService, nos puede pasar que un Xservice contenga varios controladores, rollo ActivityService, contenga, createActivity, closeActivity, mergeActivity etc... realmente no es un XService por cada caso de uso. 

Este Service hace de una especie de Proxy, o agrupador de controladores de casos de uso que tengamos .

En otro proyecto lo he llamado Gateway, es el termino que usamos en el curro cuando nos contectamos a un servicio externo, y en este caso como me conectaba a una API pues use ese termino. 

Podriamos llamar Service a los Controllers de los casos de uso, no veo ningun problema pero seria renombrar este "XController" que es el que tenemos 1 por cada caso de uso 

![image](https://user-images.githubusercontent.com/16058725/91646029-623f8c00-ea4b-11ea-97fc-494adff9d98f.png)

**Comment by plfgavilan** [comment]
En ángular también puedes modificar la vista desde el presentador, tienes formas de injectar nodos por referencia en el presentador de forma que puedes tener acceso al DOM y hacer modificaciones en la vista.  Pero es muy raro. Normalmente los presentadores no saben nada de la vista.

**Comment by plfgavilan** [comment]
> Y la segunda pregunta, ese XService, nos puede pasar que un Xservice contenga varios controladores, rollo ActivityService, contenga, createActivity, closeActivity, mergeActivity etc... realmente no es un XService por cada caso de uso.
> 
> Este Service hace de una especie de Proxy, o agrupador de controladores de casos de uso que tengamos .
> 
> En otro proyecto lo he llamado Gateway, es el termino que usamos en el curro cuando nos contectamos a un servicio externo, y en este caso como me conectaba a una API pues use ese termino.
> 
> Podriamos llamar Service a los Controllers de los casos de uso, no veo ningun problema pero seria renombrar este "XController" que es el que tenemos 1 por cada caso de uso
> 
> ![image](https://user-images.githubusercontent.com/16058725/91646029-623f8c00-ea4b-11ea-97fc-494adff9d98f.png)

Lo veo. Un service sería entonces una agrupación de controladores especificados en análisis.

**Comment by Ruskab** [comment]
Entiendo entonces en angular tampoco es habitual que el presentador conozca a la vista, habria que cambiar la direccion de esa relacion. 

y si ese Xservice lo entiendo como eso una agrupación de controladores (de casos de uso)
