### ISSUE TITLE
Integration Test Strategy [BACKEND]

### ISSUE THREAD

**Issue by plfgavilan** [rup-projects/rup-projects#213]
- [x]  ¿Testear los Recursos? ¿Con Servicios mockeados o no? 
- [x] ¿Testear los servicios? ¿Sin mockear los repositorios? Yo voto que sí.
- [x] ¿Se generan los datos con inserciones directas o usamos alguna librería de precarga de datos?

**Comment by Ruskab** [comment]
Como lo veo yo
 ¿Testear los Recursos? ¿Con Servicios mockeados o no?

depende, si luego vamos a testear desde XComponent o XServicede angular con tests de integracion, pues no haria falta testear los Resourse sin mockear. Y si testeamos los Resouses mockeados, pues no tiene mucho sentido ya que en principio no deberian de tener casi logica, solo la que toca "infrastructura/tecnologia"

 ¿Testear los servicios? ¿Sin mockear los repositorios? Yo voto que sí.
Como prefirais, quizas el flujo principal sin mockear, y el resto de casos de test, errores y caminos alternativos mockeado. 

 ¿Se generan los datos con inserciones directas o usamos alguna librería de precarga de datos?
No conozco estas librerias pero podrian ser interesantes

**Comment by plfgavilan** [comment]
Yo no lo tengo claro, pero os puedo enumerar un poco los pros y los contras que veo de una opción y otra:

En primer lugar, comentar que trataría de cumplir la pirámide de testing:
![image](https://user-images.githubusercontent.com/4791544/93003031-82874480-f53b-11ea-9eec-9b0a2d475894.png)

Cuanto más nos acercamos a la parte de arriba de la pirámide, mayor costo de mantenimiento y de tiempo de ejecución, por tanto, los tests e2e son los más jodidos de mantener y los más lentos de ejecutar. Y los tests unitarios suelen ir como un tiro y suelen ser super sencillos de mantener.

En nuestra aplicación tenemos varios bloques que podemos testear:
Frontend:

- Components
- Services

Backend:

- Resources
- Services
- Repositories

Voy a obviar por el momento los del Frontend.
En cuanto al backend, se podrían hacer los siguientes tests:

- Tests de integración desde los recursos > [muy lentos] [ muy dificiles de mantener ]  ya que levantan la aplicación completa y es más tedioso montar los objetos request y mapear los objetos response para hacer los asserts. Prueban el backend completo.
- Tests de integración desde los recursos pero mockeando los servicios [ lentos ] [ dificiles de mantener ] El sentido de estos tests es comprobar que se levantan los endpoints que esperamos que se levanten. Son más faciles de montar porque solo hace falta montar la request y la respuesta nos da igual, sólo comprobamos que devuelve un 200.
- Test de integración desde los servicios [lentos] [fáciles de mantener] Aun levantan el springContext pero es mas facil crear los datos de entrada para el servicio que para los recursos (es solo crear un dto en contraposición a crear una Request con un Dto que es mucho mas coñazo). El sentido de estos tests es comprobar nuestra logica de negocio con la capa de persistencia.
- Tests de integración de los repositorios: [Lentos] [faciles de mantener]  ya que también levantan el springContext. Pueden tener sentido cuando tenemos creados metodos mágicos o consultas complejas y queremos probar que devuelven lo que realmente esperamos. Yo por ejemplo suelo hacerlos si tengo consultas con fechas tipo "devuelveme esta entidad cuando esta fecha es mayor que tal y cual" porque a veces las consultas hacen cosas raras, y así me aseguro. Pero normalmente no los hago.
- Test unitarios del servicio, esto es, mockeando el repositorio. Estos son ridículos en la mayor parte de los casos, ya que tenemos unos servicios muy delgados en general y sii mockeamos los repositorios termínariamos comprobando que devuelve lo que le hemos pasado y acabaríamos haciendo "ping pong" tests que no valen de nada. Solo los crearía cuando realmente haya una lógica dentro del servicio más allá que llamar al repositorio y mapear la respuesta.

Dicho esto, yo optaría por una convinación de los siguientes:

- Test de integración del recurso: Muy pocos, uno por Resource. Ejemplo: MemberResource. Probar que la llamada a openMembers() devuelve un 200. Con esto te aseguras de que el recurso ha levantado y existe el endpoint base.
- Test de integración del servicio: Sólo en aquellos casos donde el servicio sea tan estúpido como llamar al repositorio y mapear la respuesta.
- Test unitarios de servicio: Siempre que el servicio tenga cierta complejidad. Evitar a toda costa ping-pong tests.


En cuanto al fronted:

- Tests unitarios de los presentadores, siempre y cuando no sean estúpidos y haya algo que probar

En cuanto a los tests e2e:
- Si los tratamos como tests de aceptación, entiendo que habría que hacer 1 por cada caso de uso. Pero sólo happy flows.
- Si nó, el sentido que tendrían es detectar que nos hemos cargado partes importantes, osea, en lugar de 1 por caso de uso, sólo testear los casos de uso más criticos y un par de los menos críticos a modo de muestreo para probar que la aplicación tira.
- Se pueden hacer tanto en java como en ts
